#!/usr/bin/env bash
# Generate nkey seeds for NATS authentication
#
# Creates 3 user nkey seeds: hub, llm-worker, monitor
# Seeds: /etc/nats/nkeys/{hub,llm-worker,monitor}.seed  (mode 0600, root:root)
# Auth config: /etc/nats/nkeys/auth.conf  (included by /etc/nats/nats.conf)
#
# Usage: sudo ./scripts/gen-nats-nkeys.sh
#
# Idempotent — skips if auth.conf already exists. Delete /etc/nats/nkeys/ to regenerate.
# To print existing public keys without regenerating: --show

set -euo pipefail

NKEYS_DIR="/etc/nats/nkeys"
NK_BIN=""

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[+]${NC} $1" >&2; }
warn()  { echo -e "${YELLOW}[!]${NC} $1" >&2; }
error() { echo -e "${RED}[x]${NC} $1" >&2; exit 1; }

SHOW_ONLY=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --show) SHOW_ONLY=true; shift ;;
    *) error "Unknown option: $1" ;;
  esac
done

[ "$(id -u)" -eq 0 ] || error "Must be run as root (sudo ./scripts/gen-nats-nkeys.sh)"

# ── show mode ──────────────────────────────────────────────────────────────
if [ "${SHOW_ONLY}" = true ]; then
  [ -f "${NKEYS_DIR}/auth.conf" ] || error "auth.conf not found — run without --show first"
  echo "Current nkey public keys:"
  grep -E 'nkey:|name:' "${NKEYS_DIR}/auth.conf"
  exit 0
fi

if [ -f "${NKEYS_DIR}/auth.conf" ]; then
  warn "auth.conf already exists — skipping. Delete ${NKEYS_DIR}/ to regenerate."
  exit 0
fi

# ── locate or download nk ──────────────────────────────────────────────────

ensure_nk() {
  if command -v nk &>/dev/null; then
    echo "nk"; return
  fi

  info "nk not found — downloading from GitHub releases..."

  # Try GitHub API for latest version; fall back to known-good version
  local version
  version=$(curl -fsSL --connect-timeout 5 \
    "https://api.github.com/repos/nats-io/nkeys/releases/latest" 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['tag_name'].lstrip('v'))" \
    2>/dev/null) || version="0.4.6"

  local arch
  arch=$(dpkg --print-architecture 2>/dev/null \
    || uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')

  local url="https://github.com/nats-io/nkeys/releases/download/v${version}/nk-v${version}-linux-${arch}.zip"
  local tmpdir
  tmpdir=$(mktemp -d)
  trap 'rm -rf "${tmpdir}"' EXIT

  curl -fsSL "${url}" -o "${tmpdir}/nk.zip" \
    || error "Failed to download nk v${version} from ${url}"

  unzip -q "${tmpdir}/nk.zip" -d "${tmpdir}"
  chmod +x "${tmpdir}/nk"

  # Verify SHA-256 if NK_SHA256 is set (get hash from github.com/nats-io/nkeys/releases)
  if [ -n "${NK_SHA256:-}" ]; then
    echo "${NK_SHA256}  ${tmpdir}/nk" | sha256sum --check \
      || error "SHA-256 mismatch for nk v${version} — update NK_SHA256 in your env"
  else
    warn "NK_SHA256 not set — skipping nk binary verification"
    warn "  Find the hash at: https://github.com/nats-io/nkeys/releases/tag/v${version}"
  fi

  # Install to /usr/local/bin for this session and future use
  cp "${tmpdir}/nk" /usr/local/bin/nk
  info "nk v${version} installed to /usr/local/bin/nk"
  echo "/usr/local/bin/nk"
}

NK_BIN=$(ensure_nk)

# ── create directories ─────────────────────────────────────────────────────

mkdir -p "${NKEYS_DIR}"
chmod 700 "${NKEYS_DIR}"
chown root:root "${NKEYS_DIR}"

# ── generate nkey pairs ────────────────────────────────────────────────────

generate_nkey() {
  local name="$1"
  local seed_file="${NKEYS_DIR}/${name}.seed"
  local tmp_seed
  tmp_seed=$(mktemp)
  trap 'rm -f "${tmp_seed}"' RETURN

  # Generate seed and save to temp file, then extract public key
  "${NK_BIN}" -gen user > "${tmp_seed}"
  local pubkey
  pubkey=$("${NK_BIN}" -inkey "${tmp_seed}" -pubout) \
    || error "Failed to derive public key for ${name} — is the nk binary valid?"

  # Move seed to final location with tight permissions
  install -m 0600 -o root -g root "${tmp_seed}" "${seed_file}"
  echo "${pubkey}"
}

info "Generating nkey pairs..."
HUB_PUB=$(generate_nkey "hub")
WORKER_PUB=$(generate_nkey "llm-worker")
MONITOR_PUB=$(generate_nkey "monitor")

# ── write auth.conf ────────────────────────────────────────────────────────

cat > "${NKEYS_DIR}/auth.conf" << EOF
# NATS nkey authorization — generated by gen-nats-nkeys.sh
# Included by /etc/nats/nats.conf
# DO NOT edit manually — regenerate with: sudo ./scripts/gen-nats-nkeys.sh

authorization {
  users: [
    { nkey: "${HUB_PUB}",    name: "hub" }
    { nkey: "${WORKER_PUB}", name: "llm-worker" }
    { nkey: "${MONITOR_PUB}", name: "monitor" }
  ]
}
EOF
chmod 640 "${NKEYS_DIR}/auth.conf"
chown root:nats "${NKEYS_DIR}/auth.conf"

info "nkeys generated at ${NKEYS_DIR}/"
info "  hub.seed        — seed for Lyra hub process       (NATS_HUB_NKEY_SEED)"
info "  llm-worker.seed — seed for Machine 2 LLM worker   (NATS_LLM_WORKER_NKEY_SEED)"
info "  monitor.seed    — seed for lyra-monitor health check (NATS_MONITOR_NKEY_SEED)"
info "  auth.conf       — public keys included by nats.conf"
warn "Set env vars in each service's run script to point at the seed files:"
warn "  export NATS_NKEY_SEED_PATH=/etc/nats/nkeys/hub.seed"
